### ISSUE TITLE
Review feedback

### ISSUE THREAD

**Issue by navidsh** [OpenLiberty/draft-guide-operator-openshift#14]
- [x] Suggestions for the following paragraph:
> "The Open Liberty Operator provides a method of deploying ... reconciling when necessary."

into
 
> The Open Liberty Operator provides a method of deploying and managing Open Liberty applications on OKD or OpenShift clusters. Open Liberty Operator introduces new Custom Resource Definitions (CRDs) including `OpenLibertyApplication`. The `OpenLibertyApplication` CRD defines a set of configurations for deploying a Liberty-based application including application image, number of instances, storage settings and etc. The Open Liberty Operator watches resources of the `OpenLibertyApplication` type and creates various Kubernetes resources such as `Deployments`, `Services`, `Routes` and etc depending on the configurations. The Operator then continuously compares the current state of the resources created and the desired state of application deployment defined in an `OpenLibertyApplication` custom resource and reconciling when necessary.

- [x] "The applicationImage parameter value is the only necessary parameter, and can be set in the format <project-name>/<image-stream-name>[:tag]."
It would be good to highlight that the `applicarionImage` can also point into an external registry such as Docker Hub and it doesn't have to be an image stream.

- [ ] General comment on the `inventory` app: it should be possible to make changes to the app to also listen to port `9080`. That way there wouldn't be any need to specify any ports in the `deploy.yaml`. Is there any reason the app can't run on `9080`?

- [ ] Defining `pullPolicy` should be actually needed. Since as soon as there is a new image in the image stream, the operator will redeploy the app automatically.

- [x] "To access the application from outside of the cluster, it needs to be exposed, which is done by setting the expose parameter to true."
It would be good to mention here that by setting `expose` to true, the operator will create a `route` resource which allows publicly accessing the app.

- [x] "Simply update the `deploy.yaml` file with the `replica: n` parameter." -> "Simply update the `deploy.yaml` file with the `replica: n` parameter with `n` being the number of instances."

- [x] Suggestion: it would be good to mention that users need to be logged into the cluster before running the commands. I know this seems obvious but I have seen people forgetting to do that in workshops.

- [x] It might be good to check if having `lights.os.fyre.ibm.com` as part of the guide is okay

**Comment by MaiHameed** [comment]
> General comment on the inventory app: it should be possible to make changes to the app to also listen to port 9080. That way there wouldn't be any need to specify any ports in the deploy.yaml. Is there any reason the app can't run on 9080?

I assume that if the port parameter is not explicitly defined that it defaults to 9080 right? If so, if we change the port from 9085 to 9080, there won't be a need for the port parameter, and I think there is value in having a small example of the parameter and its uses in the guide.

**Comment by navidsh** [comment]
> I assume that if the port parameter is not explicitly defined that it defaults to 9080 right? If so, if we change the port from 9085 to 9080, there won't be a need for the port parameter, and I think there is value in having a small example of the parameter and its uses in the guide.

Fair enough. Let's keep it as `9085`

> Could you clarify what you mean by this? Do you mean that the guide should specify the `pullPolicy` parameter as being necessary? Isn't there a default behaviour that makes the Operator redeploy the app automatically if the parameter is not specified?

Sorry, my bad. Typo in my initial comment. Defining `pullPolicy` is **NOT** needed in the example you have. The operator will redeploy the app once it detects there is a new image pushed into the `ImageStream`. Specifying `pullPolicy` is useful when the `applicationImage` parameter is pointing into an external registry such as Docker Hub.

**Comment by MaiHameed** [comment]
Addressed with #15
