### ISSUE TITLE
Content Review

### ISSUE THREAD

**Issue by GraceJansen** [OpenLiberty/draft-guide-operator-openshift#18]
What You'll Learn Section:
- OKD is not defined, only acronym used. Please define.

- reconciling - should this be reconciles instead?

Installing the Open Liberty Operator Section:
- on an OpenShift - should this be on an open shift cluster or just on open shift?

**Comment by MaiHameed** [comment]
Thanks for the feedback @GraceJansen! I opened a PR to address all of your comments, could you take a look and add a review? Thanks.

**Comment by MaiHameed** [comment]
Addressed with #20
