### ISSUE TITLE
ID review feedback

### ISSUE THREAD

**Issue by Charlotte-Holt** [OpenLiberty/draft-guide-operator-openshift#24]
Guide looks good! I've added ID feedback in the attached Word document. Let me know if you have any questions. 

[operator-guide-comments.docx](https://github.com/OpenLiberty/draft-guide-operator-openshift/files/4838997/operator-guide-comments.docx)

**Comment by MaiHameed** [comment]
Thanks for the feedback @Charlotte-Holt! 

> Just to check, is it multiple Dockerfiles the guide uses, or just one? If just one, then the last sentence could be, “Ensure you are using version 4.x because the Dockerfile in this guide uses the --chown flag, which is incompatible with older versions of Docker.”

Multiple, I kept it plural.

> Do you think the user will know which web console we’re talking about, or should we mention which web console? 

They'll know

> I also think that “Operators > OperatorHub” and “Open Liberty Operator” might be better bolded than in backticks, but up to your discretion. Could try both 

Good point! I converted them to bolded.

> By, “You can configure OpenShift to build your images from various methods.”, I’m not sure exactly what you mean. Is there any way to clarify the “from various methods” part? 

Right, I realized this sentence doesn't really add value and explaining it in detail isn't necessary, so I simplified it to:

> Create a build template to configure how to build your images.

Let me know if that doesn't make sense or needs restructuring!

> Is the registry that you’re referring to in “The image registry that is used is the internal OpenShift integrated container registry”, the OpenShift Container Registry (OCR)? If so, it should probably all be capitalized. Not sure if it’s the same thing

Yes, it's the same thing, I fixed it :)

**Comment by MaiHameed** [comment]
Updated the lgdev site here: http://lgdev1.fyre.ibm.com:4020/guides/operator-openshift.html If you would like to take a look at the changes live :) Let me know if everything looks good on the linked PR

**Comment by Charlotte-Holt** [comment]
@MaiHameed This looks great! Thanks for responding to all my feedback! :) Last thing I'd update

>Change
For example: http://inventory-guide.apps.lights.os.fyre.ibm.com/inventory/systems.
To
For example, inventory-guide.apps.lights.os.fyre.ibm.com is the HOST in the http://inventory-guide.apps.lights.os.fyre.ibm.com/inventory/systems URL.
Is this supposed to be a working URL?

No, it's an example, should I still change the sentence as you described?

Understood that it's an example URL. I'd still update to my suggestion if you're good with it.

**Comment by MaiHameed** [comment]
Updated! @Charlotte-Holt

**Comment by MaiHameed** [comment]
PR approved and merged, closing.
